
version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "3013:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3012:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
